version: '3.6'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <YOUR_MYSQL_PASSWORD>
      TZ: Europe/Istanbul
    volumes:
      - <YOUR_MYSQL_VOLUME>:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 15M
      TZ: Europe/Istanbul
  