MODE_DEV = "dev"
MODE_PROD = "prod"

MODES = [
    MODE_DEV,
    MODE_PROD,
]

MAX_ANNOUNCEMENT_NUMBER_PER_CHECK = 5

BOT_TYPE_REPLICA = "REPLICA"
BOT_TYPE_INTRODUCTION = "INTRODUCTION"

DEFAULT_CONTROL_KEY = "öğrenci"
DEFAULT_PORT = 8443
DEFAULT_MODE = "dev"
DEFAULT_BOT_TYPE = BOT_TYPE_REPLICA